package com.silverbp.android.nutrition

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Wire shape of the bundled bulk-nutrition asset
 * (`assets/nutrition/foods.v1.json.gz`), generated by
 * `tools/nutrition-import/build_nutrition_asset.py` from TFDA/USDA open data.
 * Short JSON keys keep the asset small; mapped to [NutritionRecord] for the
 * shared matcher.
 */
@Serializable
data class NutritionAssetDoc(
    val schemaVersion: Int = 0,
    val generatedAt: String = "",
    val sources: List<String> = emptyList(),
    val records: List<NutritionAssetRecord> = emptyList(),
)

@Serializable
data class NutritionAssetRecord(
    @SerialName("c") val canonicalName: String,
    @SerialName("a") val aliases: List<String> = emptyList(),
    @SerialName("na") val sodiumMgPer100g: Double,
    @SerialName("kc") val kcalPer100g: Double,
    @SerialName("p") val proteinGPer100g: Double = 0.0,
    @SerialName("f") val fatGPer100g: Double = 0.0,
    @SerialName("cb") val carbGPer100g: Double = 0.0,
    @SerialName("g") val defaultPortionGrams: Double = 100.0,
    @SerialName("u") val highSodiumUncertainty: Boolean = false,
) {
    fun toRecord(): NutritionRecord = NutritionRecord(
        canonicalName = canonicalName,
        aliases = aliases,
        sodiumMgPer100g = sodiumMgPer100g,
        kcalPer100g = kcalPer100g,
        proteinGPer100g = proteinGPer100g,
        fatGPer100g = fatGPer100g,
        carbGPer100g = carbGPer100g,
        defaultPortionGrams = defaultPortionGrams,
        highSodiumUncertainty = highSodiumUncertainty,
    )
}
